// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtAhFNTgy78sLZc0UFe866NfeooWy3UW4',
    appId: '1:424020799267:web:2b41d9d4bfc380dc296696',
    messagingSenderId: '424020799267',
    projectId: 'app-tcc-9df2b',
    authDomain: 'app-tcc-9df2b.firebaseapp.com',
    storageBucket: 'app-tcc-9df2b.appspot.com',
    measurementId: 'G-R73YDQWG3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWHOxp3_oona77tUZ1pJEOON_5fJhLzw',
    appId: '1:424020799267:android:e2b42aa7a8ce2691296696',
    messagingSenderId: '424020799267',
    projectId: 'app-tcc-9df2b',
    storageBucket: 'app-tcc-9df2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB31HIe7bVYUr4Mj9j9kKtvr_lfjBIrvcE',
    appId: '1:424020799267:ios:beb1f0b7bc0360ff296696',
    messagingSenderId: '424020799267',
    projectId: 'app-tcc-9df2b',
    storageBucket: 'app-tcc-9df2b.appspot.com',
    iosClientId: '424020799267-n2kjomc5uae68kapbf497i35aab4el75.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB31HIe7bVYUr4Mj9j9kKtvr_lfjBIrvcE',
    appId: '1:424020799267:ios:beb1f0b7bc0360ff296696',
    messagingSenderId: '424020799267',
    projectId: 'app-tcc-9df2b',
    storageBucket: 'app-tcc-9df2b.appspot.com',
    iosClientId: '424020799267-n2kjomc5uae68kapbf497i35aab4el75.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcc',
  );
}
